name: Autobuild
on:
  pull_request:
    types: [ labeled ]

jobs:
  autobuild:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'action:autobuild'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with: { node-version: 10.x }
      - run: npm install
      - run: npm run build
      - name: commit build
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "autobuild: update build"
      - name: push commit
        run: git push

      - name: remove label from pull request
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const repoParts = context.repository.split('/');
            const owner = repoParts[0];
            const repo = repoParts[1];
            const pr = context.event.number;
            console.log(`updating PR #${pr} in ${owner}/${repo}`);
            github.issues.removeLabel({
              owner,
              repo,
              pr,
              'action:autobuild',
            });
            console.log('PR updated');
